
name: First Workflow

on:
  workflow_run:
    workflows: ["Second Workflow"]
    types:
      - completed

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "This is the first job."
