
name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "This is the first job."
          sleep 5
