
name: Second Workflow

on:
  workflow_run:
    workflows: ["First Workflow"]
    types:
      - completed

jobs:
  second_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "This is the second job."
          echo "Run after first"
